spring:
  datasource:
    # jdbc:mysql://localhost:3306/test 数据库地址
    url: jdbc:mysql://120.79.197.112:3306/bbking?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root # 数据库用户名
    password: ct950916  # 数据库密码
    driver-class-name: com.mysql.jdbc.Driver  # 数据库驱动

  resources:
    static-locations: classpath:/templates/,classpath:/static/

  application:
    name:springboot-rabbitmq

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    virtual-host: /

  thymeleaf:
    cache: true
    check-template-location: true
    enabled: true
    encoding: utf-8
    prefix: /
    suffix: .html

  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000s
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    lettuce:
      shutdown-timeout: 100ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  jackson:
    time-zone: Asia/Shanghai
  #配置rabbitMq 服务器


mybatis:
  mapper-locations : classpath*:mybatis/*.xml
  type-aliases-package : com.family.bbkingdao.entity

logging:
  config: bbking-web/src/main/resources/logback.xml

#配置外部访问文件 file:/E:/fileUpload/
cbs:
  imagesPath: file:/E:/Resources/images/
  viedosPath: file:/E:/Resources/videos/
  audioPath: file:/E:/Resources/audio/
